/*
* generated by Xtext
*/
package org.xtext.dvc.sadl.ui.contentassist;

import org.xtext.dvc.sadl.ui.contentassist.AbstractSadlProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SadlProposalProvider extends AbstractSadlProposalProvider {

}
