/*
 * generated by Xtext
 */
package org.xtext.dvc.sadl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SadlUiModule extends org.xtext.dvc.sadl.ui.AbstractSadlUiModule {
	public SadlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
