/*
* generated by Xtext
*/
package org.xtext.dvc.sadl.ui.outline;



import org.eclipse.xtext.ui.editor.outline.ContentOutlineNode;
import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;
import org.xtext.dvc.sadl.sadl.AbstractConcept;

/**
 * customization of the default outline structure
 * 
 */
public class SadlTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
	  public ContentOutlineNode createNode(
	 		    AbstractConcept semanticNode,  ContentOutlineNode parentNode) {
			    ContentOutlineNode node = super.newOutlineNode(semanticNode, parentNode);
			    node.setLabel( semanticNode.eClass().getName()+": " + node.getLabel() );
			    return node;
		  }
}
