/*
 * generated by Xtext
 */
package org.xtext.dvc.sadl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SadlRuntimeModule extends org.xtext.dvc.sadl.AbstractSadlRuntimeModule {

}
